import {Navbar} from "@/components/Navbar";
import {BurgerScrollHero} from "@/components/BurgerScrollHero";
import {ArrowButton} from "@/components/ArrowButton";
import {AddToCartButton} from "@/components/cart/AddToCartButton";
import {site} from "@/data/site";
import {ArrowUpRight} from "lucide-react";
const qualities=[["ORIGINAL RECIPE","The legendary blend of 11 herbs and spices."],["REAL CHEESE","Melted over hot crispy chicken."],["FRESH BUNS","Soft, golden and toasted to order."],["SIGNATURE SAUCE","Creamy, tangy and unmistakable."]];
export default function Home(){return <main><Navbar/><BurgerScrollHero/>
<section id="stacks" className="stacks section-pad"><div className="eyebrow">01 — KFC FAVOURITES</div><h2>CHOOSE YOUR<br/><em>ZINGER.</em></h2><div className="burger-grid">{site.burgers.map((b,i)=><article className={`burger-card ${b.tone}`} key={b.name}><div className="product-art"><div role="img" aria-label={b.name} className="mini-burger" style={{backgroundImage:"url('/assets/zinger-assembled.png')"}}/><span>0{i+1}</span></div><div className="card-copy"><div><h3>{b.name}</h3><p>{b.desc}</p></div><div className="card-actions"><div className="price">Rs. {b.price.toLocaleString("en-PK")}</div><AddToCartButton item={{id:`burger-${i}`,name:b.name,price:b.price}}/></div></div></article>)}</div></section>
<section id="combos" className="combo"><div className="combo-copy"><div className="eyebrow">02 — COMPLETE THE MEAL</div><h2>MAKE IT<br/><i>A COMBO.</i></h2><p>ZINGER + KFC FRIES + AN ICE-COLD DRINK.</p><ArrowButton href="#menu">BUILD YOUR COMBO</ArrowButton></div><div className="combo-visual"><div className="fries">FRIES<span>GOLDEN / CRISP / SEASONED</span></div><div className="cup">KFC<small>ICE COLD</small></div><div className="combo-burger"/></div></section>
<section id="quality" className="quality section-pad"><div className="eyebrow">03 — THE ORIGINAL DIFFERENCE</div><h2>11 HERBS.<br/><em>11 SPICES.</em></h2><div className="quality-list">{qualities.map((x,i)=><div key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></div>)}</div></section>
<section className="manifesto"><span>HAND BREADED.</span><span>FRIED GOLDEN.</span><span className="hot">SERVED HOT.</span></section>
<section id="menu" className="menu-section section-pad"><div className="menu-head"><div><div className="eyebrow">04 — KFC MENU</div><h2>PICK YOUR<br/><em>FAVOURITE.</em></h2></div><p>Made fresh.<br/>Packed with flavour.</p></div><div className="menu-columns">{Object.entries(site.menu).map(([cat,items])=><div className="menu-cat" key={cat}><h3>{cat}</h3>{items.map(item=><div className="menu-item" key={item[0]}><div><b>{item[0]}</b><span>{item[1]}</span></div><div className="menu-buy"><strong>Rs. {Number(item[2]).toLocaleString("en-PK")}</strong><AddToCartButton compact item={{id:`${cat}-${item[0]}`.toLowerCase().replaceAll(" ","-"),name:item[0],price:Number(item[2])}}/></div></div>)}</div>)}</div></section>
<section className="fries-feature"><div><span>THE PERFECT<br/>SIDEKICK.</span><h2>DON&apos;T FORGET<br/><i>THE FRIES.</i></h2></div><div className="fries-pile">KFC<br/>FRIES<br/>FIRST.</div></section>
<section id="locations" className="locations section-pad"><div className="eyebrow">05 — FIND A RESTAURANT</div><h2>FIND YOUR<br/><em>KFC.</em></h2><div className="location-list">{site.locations.map((l,i)=><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`KFC ${l.city}`)}`} target="_blank" rel="noreferrer" key={l.city}><span>0{i+1}</span><h3>{l.city}</h3><p>{l.address}<br/>{l.hours}</p><ArrowUpRight/></a>)}</div></section>
<section id="order" className="order-cta"><div className="eyebrow">YOUR KFC FAVOURITES ARE WAITING.</div><h2>HUNGRY<br/><i>YET?</i></h2><ArrowButton light href="#stacks">ORDER NOW</ArrowButton></section>
<footer><div className="footer-brand">KFC</div><div className="footer-links"><div><b>EXPLORE</b><a href="#menu">Menu</a><a href="#locations">Restaurants</a><a href="#quality">Our food</a></div><div><b>FOLLOW</b><a href="https://instagram.com/kfc">Instagram</a><a href="https://tiktok.com/@kfc">TikTok</a></div><div><b>SUPPORT</b><a href="#quality">Ingredients</a><a href="mailto:support@example.com">Contact</a></div></div><div className="footer-bottom">KFC-STYLE CONCEPT EXPERIENCE <span>FINGER LICKIN&apos; GOOD.</span></div></footer></main>}
