import {Navbar} from "@/components/Navbar";
import {BurgerScrollHero} from "@/components/BurgerScrollHero";
import {ArrowButton} from "@/components/ArrowButton";
import {AddToCartButton} from "@/components/cart/AddToCartButton";
import {site} from "@/data/site";
import {ArrowUpRight} from "lucide-react";

const qualities=[["DOUBLE BEEF","Two juicy beef patties grilled and stacked high."],["MELTED CHEESE","Cheese layered over every beef patty."],["FRESH BUNS","Soft sesame buns, toasted to order."],["HOUSE SAUCE","Creamy signature flavour in every bite."]];

export default function Home(){return <main><Navbar/><BurgerScrollHero/>
<section id="stacks" className="stacks section-pad"><div className="eyebrow">01 — MY BURGER FAVOURITES</div><h2>MEET THE<br/><em>BURGERS.</em></h2><div className="burger-grid">{site.burgers.map((b,i)=><article className={`burger-card ${b.tone}`} key={b.name}><div className="product-art"><div role="img" aria-label={b.name} className="mini-burger"/><span>0{i+1}</span></div><div className="card-copy"><div><h3>{b.name}</h3><p>{b.desc}</p></div><div className="card-actions"><div className="price">Rs. {b.price.toLocaleString("en-PK")}</div><AddToCartButton item={{id:`burger-${i}`,name:b.name,price:b.price}}/></div></div></article>)}</div></section>
<section id="combos" className="combo"><div className="combo-copy"><div className="eyebrow">02 — GO ALL IN</div><h2>MAKE IT<br/><i>A COMBO.</i></h2><p>YUM PUM BEEF + GOLDEN FRIES + AN ICE-COLD POUR.</p><ArrowButton href="#menu">BUILD YOUR COMBO</ArrowButton></div><div className="combo-visual"><div className="fries">FRIES<span>HOT / CRISP / SEASONED</span></div><div className="cup">MY<small>BURGER · LAHORE</small></div><div className="combo-burger"/></div></section>
<section id="quality" className="quality section-pad"><div className="eyebrow">03 — BUILT DIFFERENT</div><h2>NO<br/><em>HALF MEASURES.</em></h2><div className="quality-list">{qualities.map((x,i)=><div key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></div>)}</div></section>
<section className="manifesto"><span>GRILLED FRESH.</span><span>STACKED DOUBLE.</span><span className="hot">SERVED HOT.</span></section>
<section id="menu" className="menu-section section-pad"><div className="menu-head"><div><div className="eyebrow">04 — THE MENU</div><h2>PICK YOUR<br/><em>CRAVING.</em></h2></div><p>Made fresh.<br/>Packed hot.</p></div><div className="menu-columns">{Object.entries(site.menu).map(([cat,items])=><div className="menu-cat" key={cat}><h3>{cat}</h3>{items.map(item=><div className="menu-item" key={item[0]}><div><b>{item[0]}</b><span>{item[1]}</span></div><div className="menu-buy"><strong>Rs. {Number(item[2]).toLocaleString("en-PK")}</strong><AddToCartButton compact item={{id:`${cat}-${item[0]}`.toLowerCase().replaceAll(" ","-"),name:item[0],price:Number(item[2])}}/></div></div>)}</div>)}</div></section>
<section className="fries-feature"><div><span>THE BURGER<br/>NEEDS COMPANY.</span><h2>DON&apos;T FORGET<br/><i>THE FRIES.</i></h2></div><div className="fries-pile">LOAD<br/>THE<br/>FRIES.</div></section>
<section id="locations" className="locations section-pad"><div className="eyebrow">05 — COME THROUGH</div><h2>FIND<br/><em>MY BURGER.</em></h2><div className="location-list">{site.locations.map((l,i)=><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`My Burger ${l.address} ${l.city}`)}`} target="_blank" rel="noreferrer" key={l.city}><span>0{i+1}</span><h3>{l.city}</h3><p>{l.address}<br/>{l.hours}</p><ArrowUpRight/></a>)}</div></section>
<section id="order" className="order-cta"><div className="eyebrow">YOUR DOUBLE BEEF BURGER IS WAITING.</div><h2>HUNGRY<br/><i>YET?</i></h2><ArrowButton light href="#stacks">ORDER NOW</ArrowButton></section>
<footer><div className="footer-brand">MY BURGER</div><div className="footer-links"><div><b>EXPLORE</b><a href="#menu">Menu</a><a href="#locations">Locations</a><a href="#quality">Our food</a></div><div><b>CONTACT</b><a href="tel:+923474709730">0347 4709730</a><a href="https://wa.me/923474709730" target="_blank" rel="noreferrer">WhatsApp</a></div><div><b>ORDER</b><a href="https://www.foodpanda.pk/restaurant/s3zz/my-burger-barket-market" target="_blank" rel="noreferrer">Foodpanda</a><a href="#stacks">Add to cart</a></div></div><div className="footer-bottom">UNOFFICIAL MY BURGER WEBSITE CONCEPT <span>BUILT HOT IN LAHORE.</span></div></footer></main>}
